/*
 * CLOUD API
 * IONOS Enterprise-grade Infrastructure as a Service (IaaS) solutions can be managed through the Cloud API, in addition or as an alternative to the \"Data Center Designer\" (DCD) browser-based tool.    Both methods employ consistent concepts and features, deliver similar power and flexibility, and can be used to perform a multitude of management tasks, including adding servers, volumes, configuring networks, and so on.
 *
 * The version of the OpenAPI document: 6.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TargetPortRange
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-02-01T15:22:04.229Z[Etc/UTC]")

public class TargetPortRange {
  
  public static final String SERIALIZED_NAME_END = "end";
  @SerializedName(SERIALIZED_NAME_END)
  private Integer end;


  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private Integer start;

  

  public TargetPortRange end(Integer end) {
    
    this.end = end;
    return this;
  }

   /**
   * Target port range end associated with the NAT Gateway rule.
   * @return end
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20000", value = "Target port range end associated with the NAT Gateway rule.")

  public Integer getEnd() {
    return end;
  }


  public void setEnd(Integer end) {
    this.end = end;
  }



  public TargetPortRange start(Integer start) {
    
    this.start = start;
    return this;
  }

   /**
   * Target port range start associated with the NAT Gateway rule.
   * @return start
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10000", value = "Target port range start associated with the NAT Gateway rule.")

  public Integer getStart() {
    return start;
  }


  public void setStart(Integer start) {
    this.start = start;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetPortRange targetPortRange = (TargetPortRange) o;
    return Objects.equals(this.end, targetPortRange.end) && Objects.equals(this.start, targetPortRange.start);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetPortRange {\n");
    
    sb.append("    end: ").append(toIndentedString(end)).append("\n");

    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }



// TargetPortRange instantiates a new TargetPortRange object
// This constructor makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
public TargetPortRange() {

}


}
